name: Cypress Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  cypress-run:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🧪 Executar testes Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          install: false

      - name: 📊 Fazer upload dos screenshots (em caso de falha)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: 🎥 Fazer upload dos vídeos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
